/**
 * Golden-prompt parity with the reference compilers. The golden file was
 * generated by its-compiler-python and is asserted byte-for-byte (modulo
 * line endings) by its-compiler-dotnet's GoldenPromptTests; this test keeps
 * the JS compiler in the same lockstep. If it fails, the compilers have
 * diverged - fix the divergence, do not regenerate the golden file lightly.
 */

import * as fs from 'fs';
import * as path from 'path';
import { ITSCompiler } from '../src/compiler';
import { DEFAULT_SECURITY_CONFIG } from '../src/security';

const FIXTURES = path.join(__dirname, 'fixtures');

function normalise(text: string): string {
  return text.replace(/\r\n/g, '\n').replace(/\n+$/, '');
}

describe('golden prompt parity', () => {
  it('compiles the json-types template byte-identically to the reference compilers', async () => {
    const compiler = new ITSCompiler({ ...DEFAULT_SECURITY_CONFIG, allowLocalFileSchemas: true });
    const result = await compiler.compileFile(path.join(FIXTURES, 'json-types-template.json'));
    const golden = fs.readFileSync(path.join(FIXTURES, 'golden', 'json-types-template.prompt.txt'), 'utf8');

    expect(normalise(result.prompt)).toBe(normalise(golden));
  });
});
